"""xRAG-style retrieval compression utilities."""

from .compression import (
    XRAG_TOKEN,
    XRAGCompressionResult,
    append_target_tokens,
    build_xrag_prompt_inputs,
    compression_ratio,
    compress_retrieval_embeddings,
    generate_with_xrag,
    get_retrieval_embeds,
    last_token_pool,
    prepare_inputs_embeds,
    prepare_retrieval_embeds,
    register_xrag_token,
    token_count,
    xrag_prompt,
    xrag_prompt_token_count,
)
from .modeling import Projector, SFR, XMistralConfig, XMistralForCausalLM
from .native import (
    DEFAULT_XRAG_LLM,
    DEFAULT_XRAG_RETRIEVER,
    XRAG,
    XRAGAnswer,
    XRAGConfig,
    XRAGDatastore,
    XRAGRetrieval,
    resolve_xrag_device,
)

__all__ = [
    "DEFAULT_XRAG_LLM",
    "DEFAULT_XRAG_RETRIEVER",
    "Projector",
    "SFR",
    "XRAG_TOKEN",
    "XRAG",
    "XRAGAnswer",
    "XRAGConfig",
    "XRAGCompressionResult",
    "XRAGDatastore",
    "XRAGRetrieval",
    "XMistralConfig",
    "XMistralForCausalLM",
    "append_target_tokens",
    "build_xrag_prompt_inputs",
    "compression_ratio",
    "compress_retrieval_embeddings",
    "generate_with_xrag",
    "get_retrieval_embeds",
    "last_token_pool",
    "prepare_inputs_embeds",
    "prepare_retrieval_embeds",
    "register_xrag_token",
    "resolve_xrag_device",
    "token_count",
    "xrag_prompt",
    "xrag_prompt_token_count",
]
